# rmqctl Configuration File
[RabbitMq]
Host = "localhost"
Port = 5672
VirtualHost = "/"
User = "guest"
Password = "guest"
Exchange = "amq.direct"
ClientName = "rabbit-cli-tool"
PrefetchCount = 200

[FileConfig]
MessagesPerFile = 10000