# rmq Configuration File
# This file contains default settings for the rmq CLI tool
[RabbitMq]
Host = "localhost"
Port = 5672
VirtualHost = "/"
User = "guest"
Password = "guest"
Exchange = "amq.direct"
ClientName = "rabbit-cli-tool"

[FileConfig]
MessagesPerFile = 10000
## Default value is the OS specific newline character
# MessageDelimiter="\n"
